import type { Metadata } from "next";
import SiteShell from "@/components/SiteShell";

export const metadata: Metadata = {
  title: "Terms of Use (2026)",
  description: "PupVax 2026 terms of use. Vaccine schedules are generalized estimates for educational purposes only. Not veterinary advice.",
  alternates: { canonical: "https://pupvax.com/terms" },
};

export default function Terms() {
  return (
    <SiteShell>
      <div className="mx-auto max-w-3xl px-4 py-10 prose prose-stone">
        <h1>Terms of Use</h1>
        <p><strong>Last updated: June 26, 2026</strong></p>
        <p>
          By using PupVax (pupvax.com) you agree to these terms. The site is provided free of charge,
          &quot;as is,&quot; for general informational purposes.
        </p>
        <h2>Medical disclaimer</h2>
        <p>
          PupVax provides generalized 2026 dog vaccine, deworming and heartworm schedules for
          educational purposes only. It is <strong>not</strong> a substitute for professional
          veterinary advice, diagnosis or treatment. The dates and recommendations the tool generates
          are estimates based on AAHA and AVMA standard schedules and do not account for your
          dog&apos;s individual history, breed-specific risks, health status, medication interactions
          or local disease pressure. Always consult a licensed veterinarian before making decisions
          about your dog&apos;s vaccinations or health. We make no guarantee of accuracy and are not
          liable for any outcome resulting from the use of this information. If you believe your dog
          has a medical emergency, contact your veterinarian or an emergency animal hospital immediately.
        </p>
        <h2>Your saved data</h2>
        <p>
          Dog profiles you create (name, birth date, breed) are stored only in your own browser using
          localStorage. We do not receive, store, back up or have any access to this data. You are
          solely responsible for maintaining your own records. Clearing your browser data will delete
          your dog profiles.
        </p>
        <h2>Intellectual property</h2>
        <p>
          All content on PupVax including text, schedules, breed-specific data, and the vaccine
          schedule tool is protected by copyright. You may use the schedules and guides for personal,
          non-commercial purposes. You may not scrape, republish, redistribute or resell the content
          in bulk without written permission. Short excerpts with attribution and a link back to
          PupVax are permitted.
        </p>
        <h2>Third-party services</h2>
        <p>
          PupVax uses Google Analytics and Google AdSense. These services have their own terms of
          service and privacy policies which you should review. We are not responsible for the
          practices of third-party services.
        </p>
        <h2>Limitation of liability</h2>
        <p>
          PupVax is provided on an &quot;as is&quot; and &quot;as available&quot; basis. We make no
          warranties, express or implied, regarding the accuracy, completeness or reliability of any
          vaccine schedule, date, or recommendation generated by the tool. To the fullest extent
          permitted by law, we disclaim all liability for any damages arising from your use of or
          reliance on PupVax.
        </p>
        <h2>Changes to these terms</h2>
        <p>
          We may update these terms at any time without prior notice. Changes take effect when posted.
          Continued use of the site after changes are posted means you accept the updated terms.
          Check this page periodically for updates.
        </p>
        <h2>Governing law</h2>
        <p>
          These terms are governed by the laws of the United States. Any disputes shall be resolved
          in the courts of competent jurisdiction.
        </p>
      </div>
    </SiteShell>
  );
}
